apiDir: "../rest-builder-api/src/main/java"
apiPackagePath: "com.train.liferay.restBuilder"
application:
    baseURI: "/rest-builder"
    className: "RestBuilderApplication"
    name: "RestBuilder"
author: "DEEPAK SINGH JANGRA"
clientDir: "../rest-builder-client/src/main/java"
testDir: "../rest-builder-test/src/testIntegration/java"